name: radar
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1
environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.19.6"

  # sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  rxdart_ext: ^0.3.0
  listenable_stream: ^2.0.1
  google_api_headers: ^4.0.3
  http: ^1.2.2
  rxdart: ^0.27.2
  # rxdart: ^0.28.0
  collection: ^1.18.0
  flutter_bloc_pattern: ^3.0.0
  meta: ^1.11.0

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.4.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.2.3
  location: ^7.0.1
  flutter_polyline_points: ^2.1.0
  fluttericon: ^2.0.0
  cloud_firestore: ^5.4.4
  flutter_launcher_icons: ^0.14.1
  flutter_rating_bar: ^4.0.1
  geolocator: ^13.0.1
  baseflow_plugin_template: ^2.1.1
  flutter_riverpod: ^2.3.1
  lottie: ^3.1.3
  fab_circular_menu: ^1.0.2
  flip_card: ^0.7.0
  flutter_rating_stars: ^1.0.3+4
  geocoding: ^3.0.0
  firebase_auth: ^5.3.1
  firebase_phone_auth_handler: ^1.0.8
  pinput: ^5.0.0
  intl_phone_field: ^3.1.0
  syncfusion_flutter_maps: ^28.1.35
  firebase_database: ^11.1.4
  custom_marker: ^1.0.0
  get: ^4.6.5
  # flutter_google_maps_webservices: ^1.1.1
  file_picker: ^8.1.3
  firebase_storage: ^12.3.4
  image_picker: ^1.1.2
  flutter_svg: ^1.0.1
  multi_select_flutter: ^4.1.3
  url_launcher: ^6.1.10
  carousel_slider: ^5.0.0
  cached_network_image: ^3.2.3
  flutter_glow: ^0.3.0
  intl: ^0.20.1
  flutter_swipe_detector: ^2.0.0
  top_snackbar_flutter: ^3.0.0+1
  go_router: ^14.3.0
  firebase_messaging: ^15.1.3
  overlay_support: ^2.1.0
  cloud_functions: ^5.1.3
  # flutter_local_notifications: ^17.2.4
  cloud_functions_web: ^4.10.2
  firebase_core: ^3.6.0
  google_maps_flutter_web: ^0.5.10
  google_places_flutter: ^2.0.9
  country_code_picker: ^3.1.0
  flutter_google_places_hoc081098: ^2.0.0
  image: ^4.3.0
  flutter_image_compress: ^2.3.0
dependency_overrides:
  rxdart: ^0.28.0

flutter_native_splash:
  # Background color of the splash screen
  color: "#BCE566"

  # Path to the image for the splash screen
  image: assets/images/logo-empty.png

  # Android-specific configurations
  android: true # Ensure this is set to true or false (avoid leaving it out)

  # iOS-specific configurations
  ios: true # Same as above, should be true or false

  # Android 12+ specific configurations
  android_12:
    image: assets/images/logo-empty.png
    color: "#BCE566"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/mapicons/
    - assets/svg/
    - assets/images/
    - assets/json/
    - assets/animassets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
